version: "3.8"

services:
    memcached:
      image: memcached:1.6.17-alpine
      restart: always
      ports:
        - "11211:11211"
      networks:
        - v_network
    web:
        build: ./web
        volumes:
          - ./src:/web
        ports:
          - "8080:8080"
        networks:
          - v_network
    client:
        build: ./client
        volumes:
          - ./src:/client
        ports:
          - "8081:8081"
        networks:
          - v_network
networks:
  v_network:
    driver: bridge