version: "3.8"

services:
    memcached:
      hostname: memcached
      image: memcached:1.6.17-alpine
      restart: always
      ports:
        - "11211:11211"
      networks:
        - v_network
    viewer:
        hostname: viewer
        build: ./viewer
        environment:
          - MEMCHACHED_HOST=memcached
          - MEMCHACHED_PORT=11211
        volumes:
          - ./src:/viewer
        ports:
          - "8080:8080"
        networks:
          - v_network
    subscriber:
        hostname: subscriber
        build: ./subscriber
        environment:
          - MEMCHACHED_HOST=memcached
          - MEMCHACHED_PORT=11211
          - MQTT_HOST=10.2.0.40
          - MQTT_LOGIN=zigstar
          - MQTT_PASSWORD=zigstar
        volumes:
          - ./src:/subscriber
        ports:
          - "8081:8081"
        networks:
          - v_network
networks:
  v_network:
    driver: bridge